apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
       app: myapp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: web-volume
  nodeSelector:
      kubernetes.io/hostname: minikube-m02
  volumes:
    - name: web-volume
      hostPath:
        path: /home/docker/podVolume/
        type: Directory
