apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
       app: myapp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
        - containerPort: 80
    readinessProbe:
        initialDelaySeconds: 1
        periodSeconds: 2
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 1
        httpGet:
           host:
           scheme: HTTP
           path: /
           port: 8080
