apiVersion: v1
kind: Service
metadata:
    name: nodeport-service
spec:
    type: NodePort
    selector:
        app: myapp
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30200
