apiVersion: v1
kind: Service
metadata:
    name: lb-service
spec:
    type: LoadBalancer
    externalIPs:				# Not mandatory if using cloud
        - 192.168.99.111
    selector:
        app: backend
    ports:
        - name: http
          protocol: TCP
          port: 80          # Service port
          targetPort: 80    # Container port
